server:
  port: ${SERVER_PORT:9900}

spring:
  application:
    name: discovery-server

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${SERVER_PORT:9900}/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 0
    response-cache-update-interval-ms: 5000

logging:
  level:
    com.netflix.eureka: WARN
    com.netflix.discovery: WARN
