server:
  port: ${SERVER_PORT:9907}

spring:
  application:
    name: wishlist-service
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:defaultdb}?useSSL=true&requireSSL=true&trustServerCertificate=true
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        jdbc:
          time_zone: UTC

  flyway:
    enabled: true
    baseline-on-migrate: ${SPRING_FLYWAY_BASELINE_ON_MIGRATE:true}
    baseline-version: 0
    validate-on-migrate: false
    locations: classpath:db/migration
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:9900/eureka/}
  instance:
    prefer-ip-address: true

logging:
  level:
    com.entitykart: INFO
